/*
 * SPI_Pb.h
 *
 * Created: 12/20/2019 3:25:15 PM
 *  Author: Zeyad
 */ 
 #include "SPI_Pb.h"

 Str_SPIConfiguration_t SPI_TX = {MASTER,NORMAL_SPEED,PRE_SCALER_F_16,POLLING,SAMPLE_LEAD,MSB,POLARITY_LOW};
 Str_SPIConfiguration_t SPI_RX = {SLAVE ,NORMAL_SPEED,PRE_SCALER_F_16,POLLING,SAMPLE_LEAD,MSB,POLARITY_LOW}; 

